@hostname=localhost
@port=4000
@host={{hostname}}:{{port}}

### Crear usuario
POST http://{{host}}/api/v1/users
Content-Type: application/json

{
    "name": "Abel Romero Ruiz",
    "username": "abel",
    "email":"abel@gmail.com",
    "password": "123456",
    "address": "Av. pablo silva gacia"
}

###Actualizar usario
PUT http://{{host}}/api/v1/users/60e0a7c9dc78212eec28a22d
Content-Type: application/json

{
    "name": "Abel Ruiz",
    "username": "abel",
    "email":"abel@gmail.com",
    "password": "123456",
    "address": "Av. pablo silva gacia"
}

### Eliminar usuario
DELETE http://{{host}}/api/v1/users/60e0a5d270da092ba49ff4d7

### Obtener usario
GET  http://{{host}}/api/v1/users/60e0a5d270da092ba49ff4d7

### Obtener usuarios
GET  http://{{host}}/api/v1/users?page=0&size=5